batch_size : 64
lr : 0.001
num_epochs : 300

input_dim : 1    
lstm_hidden_dim : 2
lstm_layer_dim : 2
layer1_class : 20
layer2_class : 10
layer3_class : 2
layer1_reg : 800
seq_dim : 701
path_data : 'D:\Papers\Multitask_network\data\clean_data\'
path_results : 'D:\Papers\Multitask_network\results\'

mode : 'train'
train_from_scratch : True
